version: "2"

services:

  portainer:
    image: portainer/portainer
    privileged: true
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
    ports:
     - "8000:8000"

volumes:
  portainer_data:

networks:
  default:
      name: proxy