version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    privileged: true
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped

networks:
  default:
    external:
      name: proxy